CREATE TABLE interview_rounds (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    position_id BIGINT NOT NULL,
    round_name VARCHAR(80) NOT NULL,
    round_number INT NOT NULL,
    interview_type VARCHAR(16) NOT NULL,
    starts_at DATETIME(6) NULL,
    ends_at DATETIME(6) NULL,
    location VARCHAR(500) NULL,
    result VARCHAR(20) NOT NULL,
    process_notes VARCHAR(4000) NULL,
    review_summary VARCHAR(4000) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_rounds_position_number (position_id, round_number),
    KEY ix_rounds_user (user_id),
    CONSTRAINT fk_rounds_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_rounds_position FOREIGN KEY (position_id) REFERENCES positions(id) ON DELETE CASCADE,
    CONSTRAINT ck_rounds_type CHECK (interview_type IN ('PHONE', 'VIDEO', 'ONSITE', 'WRITTEN_TEST', 'OTHER')),
    CONSTRAINT ck_rounds_result CHECK (result IN ('UPCOMING', 'AWAITING_RESULT', 'PASSED', 'FAILED', 'CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE interview_questions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    round_id BIGINT NOT NULL,
    sort_order INT NOT NULL,
    question VARCHAR(2000) NOT NULL,
    answer VARCHAR(4000) NULL,
    category VARCHAR(40) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY ix_questions_round (round_id),
    KEY ix_questions_user (user_id),
    CONSTRAINT fk_questions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_questions_round FOREIGN KEY (round_id) REFERENCES interview_rounds(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE schedule_events (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    event_type VARCHAR(20) NOT NULL,
    starts_at DATETIME(6) NULL,
    ends_at DATETIME(6) NULL,
    position_id BIGINT NULL,
    interview_round_id BIGINT NULL,
    location VARCHAR(500) NULL,
    notes VARCHAR(2000) NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    manual_urgency VARCHAR(16) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY ix_schedules_user_time (user_id, starts_at),
    KEY ix_schedules_user_status (user_id, status),
    KEY ix_schedules_position (position_id),
    KEY ix_schedules_round (interview_round_id),
    CONSTRAINT fk_schedules_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_schedules_position FOREIGN KEY (position_id) REFERENCES positions(id) ON DELETE CASCADE,
    CONSTRAINT fk_schedules_round FOREIGN KEY (interview_round_id) REFERENCES interview_rounds(id) ON DELETE CASCADE,
    CONSTRAINT ck_schedules_type CHECK (event_type IN ('INTERVIEW', 'WRITTEN_TEST', 'ASSESSMENT', 'APPLY_DEADLINE', 'OFFER_DEADLINE', 'CUSTOM')),
    CONSTRAINT ck_schedules_status CHECK (status IN ('PENDING', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_schedules_manual_urgency CHECK (manual_urgency IS NULL OR manual_urgency IN ('URGENT', 'APPROACHING', 'NORMAL'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
